name: Build & Commit GitHub Action

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'dist/**' # avoid infinite loops

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '23'

      - run: npm ci
      - run: npm run build

      - name: Commit compiled files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/
          git commit -m "chore: auto-compile action" || echo "No changes to commit"
          git push
